let iconSource = {
    "60-round mags for AK": "",
    "Lower half-mask": "",
    "Knives Bars A-2607": "",
    "AK-74N": "",
    "M4A1 assault rifle": "",
    "PM pistol": "",
    "PMC USEC dogtag": "",
    "PMC BEAR dogtag": "",
    "M67 grenade": "",
    "Military battery": "",
    "30-mil. shells for BMP cannon": "",
    "Salewa kit": "",
    "Gas analyzer": "https://gamepedia.cursecdn.com/escapefromtarkov_gamepedia/1/1d/Gas_Analyzer_Icon.png?version=872bbde216119a08b270d6b1357d0292",
    "Morphine injector": "",
    "Cans of meat": "",
    "Car battery": "https://gamepedia.cursecdn.com/escapefromtarkov_gamepedia/a/a0/Car_Battery_Icon.png?version=d8c81e29fdfd0762ff32fdfd806504e5",
    "Spark plug": "",
    "303 dorm room key": "",
    "ZB-014 key": "",
    "The customs military checkpoint key": "",
    "Gas station closet key": "",
    "Secure Flash drive": "",
    "Medical bloodset": "",
    "Respirator": "",
    "False flash drive": "",
    "MRE ration pack": "",
    "WD-40 100ml": "",
    "Clin wiper": "",
    "Corrugated hose": "",
    "Ox bleach": "",
    "The key from the locked resort rooms": "",
    "Heat-exchange alkali surface washer": "",
    "5L propane tank": "",
    "Military COFDM wireless Signal Transmitter": "",
    "Virtex programmable processor": "",
    "Powercord": "",
    "T-Shaped Plug": "",
    "Printed circuit board": "",
    "Graphics card": "",
    "CPU Fan": "",
    "PC CPU": "",
    "Rechargeable battery": "",
    "Broken GPhone": "",
    "Malboro cigarette": "",
    "Strike cigarette": "",
    "Wilston cigarette": "",
    "UHF RFID Reader": "",
    "VPX Flash Storage Module": "",
    "Wires": "",
    "Capacitors": "",
    "Ski hat with holes for eyes": "",
    "Pilgrim tourist backpack": "",
    "Wartech (TV-109, TV-106)": "",
    "BlackRock chest rig": "",
    "Fuel conditioner": "",
    "Bronze lion": "",
    "Horse figurine": "",
    "Cat figurine": "",
    "Roler submariner gold wrist watch": "",
    "Antique teapot": "",
    "Antique vase": "",
    "Aramid fabric": "",
    "Ripstop fabric": "",
    "Paracord": "",
    "Fleece fabric": "",
    "Polyaramide cordura fabric": "",
    "KEKtape": "",
    "Golden TT": "",
    "Killa's helmet": "",
    "Shturman's key": "",
    "Portable defibrillator": "",
    "CMS surgery kit": "",
    "Flash drive": "",
    "TerraGroup Labs access keycard": "",
    "Old firesteel": "",
    "Antique axe": "",
    "Battered antique Book": "",
    "FireKlean gun lube": "",
    "Golden rooster": "",
    "Silver Badge": "",
    "Deadlyslob's beard oil": "",
    "Golden 1GPhone": "",
    "Jar of DevilDog mayo": "",
    "Can of sprats": "",
    "Fake mustache": "",
    "Kotton beanie": "",
    "Can of Dr. Lupo's coffee beans": "",
    "Pestily plague mask": "",
    "Raven figurine": "",
    "Shroud half-mask": ""
}

let materialShortNameList = {
    "60-round mags for AK": "",
    "Lower half-mask": "",
    "Knives Bars A-2607": "",
    "AK-74N": "",
    "M4A1 assault rifle": "",
    "PM pistol": "",
    "PMC USEC dogtag": "",
    "PMC BEAR dogtag": "",
    "M67 grenade": "",
    "Military battery": "",
    "30-mil. shells for BMP cannon": "",
    "Salewa kit": "",
    "Gas analyzer": "GasAn",
    "Morphine injector": "",
    "Cans of meat": "",
    "Car battery": "Baterry",
    "Spark plug": "",
    "303 dorm room key": "",
    "ZB-014 key": "",
    "The customs military checkpoint key": "",
    "Gas station closet key": "",
    "Secure Flash drive": "",
    "Medical bloodset": "",
    "Respirator": "",
    "False flash drive": "",
    "MRE ration pack": "",
    "WD-40 100ml": "",
    "Clin wiper": "",
    "Corrugated hose": "",
    "Ox bleach": "",
    "The key from the locked resort rooms": "",
    "Heat-exchange alkali surface washer": "",
    "5L propane tank": "",
    "Military COFDM wireless Signal Transmitter": "",
    "Virtex programmable processor": "",
    "Powercord": "",
    "T-Shaped Plug": "",
    "Printed circuit board": "",
    "Graphics card": "",
    "CPU Fan": "",
    "PC CPU": "",
    "Rechargeable battery": "",
    "Broken GPhone": "",
    "Malboro cigarette": "",
    "Strike cigarette": "",
    "Wilston cigarette": "",
    "UHF RFID Reader": "",
    "VPX Flash Storage Module": "",
    "Wires": "",
    "Capacitors": "",
    "Ski hat with holes for eyes": "",
    "Pilgrim tourist backpack": "",
    "Wartech (TV-109, TV-106)": "",
    "BlackRock chest rig": "",
    "Fuel conditioner": "",
    "Bronze lion": "",
    "Horse figurine": "",
    "Cat figurine": "",
    "Roler submariner gold wrist watch": "",
    "Antique teapot": "",
    "Antique vase": "",
    "Aramid fabric": "",
    "Ripstop fabric": "",
    "Paracord": "",
    "Fleece fabric": "",
    "Polyaramide cordura fabric": "",
    "KEKtape": "",
    "Golden TT": "",
    "Killa's helmet": "",
    "Shturman's key": "",
    "Portable defibrillator": "",
    "CMS surgery kit": "",
    "Flash drive": "",
    "TerraGroup Labs access keycard": "",
    "Old firesteel": "",
    "Antique axe": "",
    "Battered antique Book": "",
    "FireKlean gun lube": "",
    "Golden rooster": "",
    "Silver Badge": "",
    "Deadlyslob's beard oil": "",
    "Golden 1GPhone": "",
    "Jar of DevilDog mayo": "",
    "Can of sprats": "",
    "Fake mustache": "",
    "Kotton beanie": "",
    "Can of Dr. Lupo's coffee beans": "",
    "Pestily plague mask": "",
    "Raven figurine": "",
    "Shroud half-mask": ""
};