let iconSource = {
    "60-round mags for AK": "",
    "Lower half-mask": "",
    "Knives Bars A-2607": "",
    "AK-74N": "",
    "M4A1 assault rifle": "",
    "PM pistol": "",
    "PMC USEC dogtag": "",
    "PMC BEAR dogtag": "",
    "M67 grenade": "",
    "Military battery": "",
    "30-mil. shells for BMP cannon": "",
    "Salewa kit": "",
    "Gas analyzer": "https://gamepedia.cursecdn.com/escapefromtarkov_gamepedia/1/1d/Gas_Analyzer_Icon.png?version=872bbde216119a08b270d6b1357d0292",
    "Morphine injector": "",
    "Cans of meat": "",
    "Car battery": "https://gamepedia.cursecdn.com/escapefromtarkov_gamepedia/a/a0/Car_Battery_Icon.png?version=d8c81e29fdfd0762ff32fdfd806504e5",
    "Spark plug": "https://gamepedia.cursecdn.com/escapefromtarkov_gamepedia/4/46/Spark_Plug_Icon_.png?version=5d679b96f39a59d595f8bf4763197f7b",
    "303 dorm room key": "",
    "ZB-014 key": "",
    "The customs military checkpoint key": "",
    "Gas station closet key": "",
    "Secure Flash drive": "https://gamepedia.cursecdn.com/escapefromtarkov_gamepedia/b/b7/Secure_Flash_drive_Icon.png?version=dee0172505650e34c8dc4c404de6f78a",
    "Medical bloodset": "https://gamepedia.cursecdn.com/escapefromtarkov_gamepedia/5/56/Medical_Bloodset_Icon.png?version=ac89775bb1d6ad64a4aa613c2ccd16ef",
    "Respirator": "",
    "False flash drive": "",
    "MRE ration pack": "",
    "WD-40 100ml": "https://gamepedia.cursecdn.com/escapefromtarkov_gamepedia/0/06/WD40_100ml_Icon.png?version=fe060e6a9776fe1185a02b85ecf3e62c",
    "Clin wiper": "",
    "Corrugated hose": "https://gamepedia.cursecdn.com/escapefromtarkov_gamepedia/b/b0/Hoseicon.png?version=51c20ce935ad10ea15ecc7fcd1740972",
    "Ox bleach": "",
    "The key from the locked resort rooms": "",
    "Heat-exchange alkali surface washer": "",
    "5L propane tank": "",
    "Military COFDM wireless Signal Transmitter": "https://gamepedia.cursecdn.com/escapefromtarkov_gamepedia/3/3a/COFDM_Icon.png?version=ee091fd6b714c295a3efb78d0a40cdc6",
    "Virtex programmable processor": "",
    "Powercord": "https://gamepedia.cursecdn.com/escapefromtarkov_gamepedia/e/e1/Powercord_icon.png?version=46674cf442f8527d0fe891e7dd119742",
    "T-Shaped Plug": "",
    "Printed circuit board": "https://gamepedia.cursecdn.com/escapefromtarkov_gamepedia/c/c5/Circuit_Icon.png?version=b7767a9f8946d4cdea1229e1965a4719",
    "Graphics card": "",
    "CPU Fan": "https://gamepedia.cursecdn.com/escapefromtarkov_gamepedia/a/a8/CPU_Fan_Icon.png?version=34e6413f54d8c63fa71ed212d3bd13e7",
    "PC CPU": "",
    "Rechargeable battery": "",
    "Broken GPhone": "",
    "Malboro cigarette": "",
    "Strike cigarette": "",
    "Wilston cigarette": "",
    "UHF RFID Reader": "",
    "VPX Flash Storage Module": "https://gamepedia.cursecdn.com/escapefromtarkov_gamepedia/8/88/VPXFlashIcon.png?version=f2bb2c2668325034d17649a3035fa521",
    "Wires": "https://gamepedia.cursecdn.com/escapefromtarkov_gamepedia/a/a4/Wiresicon.png?version=5290c686201f2318562959de42ff4987",
    "Capacitors": "https://gamepedia.cursecdn.com/escapefromtarkov_gamepedia/e/e3/Capacitorsicon.png?version=0ddb687554a65933ef7fed323b594975",
    "Ski hat with holes for eyes": "",
    "Pilgrim tourist backpack": "",
    "Wartech (TV-109, TV-106)": "",
    "BlackRock chest rig": "",
    "Fuel conditioner": "",
    "Bronze lion": "https://gamepedia.cursecdn.com/escapefromtarkov_gamepedia/c/c2/Bronze_Lion_Icon.png?version=494122a8dd8fb9eb12f6d7844d1e1a79",
    "Horse figurine": "",
    "Cat figurine": "",
    "Roler submariner gold wrist watch": "https://gamepedia.cursecdn.com/escapefromtarkov_gamepedia/e/e7/Roler_icon.png?version=3c5ff721928e60443cc4c8bc63f5f7bc",
    "Antique teapot": "",
    "Antique vase": "",
    "Aramid fabric": "",
    "Ripstop fabric": "",
    "Paracord": "",
    "Fleece fabric": "",
    "Polyaramide cordura fabric": "",
    "KEKtape": "",
    "Golden TT": "",
    "Killa's helmet": "",
    "Shturman's key": "",
    "Portable defibrillator": "",
    "CMS surgery kit": "",
    "Flash drive": "",
    "TerraGroup Labs access keycard": "",
    "Old firesteel": "",
    "Antique axe": "",
    "Battered antique Book": "",
    "FireKlean gun lube": "",
    "Golden rooster": "",
    "Silver Badge": "",
    "Deadlyslob's beard oil": "",
    "Golden 1GPhone": "",
    "Jar of DevilDog mayo": "",
    "Can of sprats": "",
    "Fake mustache": "",
    "Kotton beanie": "",
    "Can of Dr. Lupo's coffee beans": "",
    "Pestily plague mask": "",
    "Raven figurine": "",
    "Shroud half-mask": ""
}

let materialShortNameList = {
    "60-round mags for AK": "",
    "Lower half-mask": "",
    "Knives Bars A-2607": "",
    "AK-74N": "",
    "M4A1 assault rifle": "",
    "PM pistol": "",
    "PMC USEC dogtag": "",
    "PMC BEAR dogtag": "",
    "M67 grenade": "",
    "Military battery": "",
    "30-mil. shells for BMP cannon": "",
    "Salewa kit": "",
    "Gas analyzer": "GasAn",
    "Morphine injector": "",
    "Cans of meat": "",
    "Car battery": "Baterry",
    "Spark plug": "Plug",
    "303 dorm room key": "",
    "ZB-014 key": "",
    "The customs military checkpoint key": "",
    "Gas station closet key": "",
    "Secure Flash drive": "Flash drive",
    "Medical bloodset": "Bloodset",
    "Respirator": "",
    "False flash drive": "",
    "MRE ration pack": "",
    "WD-40 100ml": "WD-40",
    "Clin wiper": "",
    "Corrugated hose": "Hose",
    "Ox bleach": "",
    "The key from the locked resort rooms": "",
    "Heat-exchange alkali surface washer": "",
    "5L propane tank": "",
    "Military COFDM wireless Signal Transmitter": "SG-C10",
    "Virtex programmable processor": "",
    "Powercord": "Cord",
    "T-Shaped Plug": "",
    "Printed circuit board": "Circuit board",
    "Graphics card": "",
    "CPU Fan": "CPU Fan",
    "PC CPU": "",
    "Rechargeable battery": "",
    "Broken GPhone": "",
    "Malboro cigarette": "",
    "Strike cigarette": "",
    "Wilston cigarette": "",
    "UHF RFID Reader": "",
    "VPX Flash Storage Module": "VPX",
    "Wires": "Wires",
    "Capacitors": "Cap.",
    "Ski hat with holes for eyes": "",
    "Pilgrim tourist backpack": "",
    "Wartech (TV-109, TV-106)": "",
    "BlackRock chest rig": "",
    "Fuel conditioner": "",
    "Bronze lion": "Lion",
    "Horse figurine": "",
    "Cat figurine": "",
    "Roler submariner gold wrist watch": "Roler",
    "Antique teapot": "",
    "Antique vase": "",
    "Aramid fabric": "",
    "Ripstop fabric": "",
    "Paracord": "",
    "Fleece fabric": "",
    "Polyaramide cordura fabric": "",
    "KEKtape": "",
    "Golden TT": "",
    "Killa's helmet": "",
    "Shturman's key": "",
    "Portable defibrillator": "",
    "CMS surgery kit": "",
    "Flash drive": "",
    "TerraGroup Labs access keycard": "",
    "Old firesteel": "",
    "Antique axe": "",
    "Battered antique Book": "",
    "FireKlean gun lube": "",
    "Golden rooster": "",
    "Silver Badge": "",
    "Deadlyslob's beard oil": "",
    "Golden 1GPhone": "",
    "Jar of DevilDog mayo": "",
    "Can of sprats": "",
    "Fake mustache": "",
    "Kotton beanie": "",
    "Can of Dr. Lupo's coffee beans": "",
    "Pestily plague mask": "",
    "Raven figurine": "",
    "Shroud half-mask": ""
};